#!/usr/bin/env node
'use strict';

process.title = 'ALKS';

var program = require('commander'),
    clc     = require('cli-color'),
    _       = require('underscore'),
    async   = require('async'),
    prompt  = require('prompt'),
    request = require('request'),
    config  = require('../package.json'),
    utils   = require('./utils');

var durationValues = [ 2, 6, 12, 18, 24, 36 ],
    outputValues   = [ 'json', 'env', 'docker' ];

program
    .version(config.version)
    .description('creates a new session')
    .option('-p, --password [password]', 'my password')
    .option('-d, --duration [hours]', 'duration of session (' + durationValues.join(', ') + ')', durationValues[0])
    .option('-o, --output [format]', 'output format (' + outputValues.join(', ') + ')', outputValues[0])
    .parse(process.argv);

var password = program.password,
    duration = parseInt(program.duration),
    output   = program.output;

if(!_.contains(durationValues, duration)){
    utils.errorAndExit('The duration provided ('+duration+') is not in the allowed values: ' + durationValues.join(', '));
}

if(!_.contains(outputValues, output)){
    utils.errorAndExit('The output provided ('+output+') is not in the allowed values: ' + outputValues.join(', '));
}

async.waterfall([
    /// first handle the password
    function(callback){
        // if its empty then prompt them
        if(_.isEmpty(password)){
            prompt.start();
            prompt.message = '';
            prompt.get([{
                name: 'password',
                description: 'Password for ' + utils.getConfig().ALKS_USERID,
                hidden: true,
                required: true
            }], function(err, result){
                if(err){
                    callback(err);
                }
                else{
                    callback(null, result.password);
                }
            });
        }
        // otherwise just return the provided password
        else{
            callback(null, password);
        }
    },
    // now call the ALKS API
    function(password, callback){
        var payload = _.extend(
            {
                password: password,
                sessionTime: duration
            },
            utils.getConfigForRequest()
        );

        request({
            url: utils.getConfig().ALKS_SERVER + '/getKeys/',
            method: 'POST',
            json: payload
        }, function(err, results){
            if(err){
                return callback(err);
            }
            else if(results.statusCode !== 200){
                return callback(results.body.statusMessage);
            }
            
            callback(null, {
                access_key:    results.body.accessKey,
                secret_key:    results.body.secretKey,
                session_token: results.body.sessionToken
            });
        });
    },
    // now deal with the session data
    function(sessionData, callback){
        var expires = new Date();
        expires.setHours(expires.getHours()+duration);
        console.error(clc.white('Your AWS session data has been generated and expires ' + expires));
        
        if(output === 'docker'){
            console.log([
                ' -e AWS_ACCESS_KEY_ID=', sessionData.access_key,
                ' -e AWS_SECRET_ACCESS_KEY=', sessionData.secret_key,
                ' -e AWS_SESSION_TOKEN=', sessionData.session_token
            ].join(''));
        }
        else if(output === 'env'){
            var cmd = utils.isWindows() ? 'SET' : 'export'
            console.log([
                cmd, ' AWS_ACCESS_KEY_ID=', sessionData.access_key, ' && ',
                cmd, ' AWS_SECRET_ACCESS_KEY=', sessionData.secret_key, ' && ',
                cmd, ' AWS_SESSION_TOKEN=', sessionData.session_token
            ].join(''));
        }
        else{
            console.log(JSON.stringify(sessionData, null, 4));
        }
    }
], function(err, data){
    if(err){
        utils.errorAndExit(err);
    }
});